<?php

use Drupal\Core\Template\Attribute;

function workshop_theme($existing, $type, $theme, $path)
{
    return [
        'workshop_region_placeholder' => [
            'variables' => [
                'region' => '',
                'label' => '',
            ],
        ],
    ];
}

function workshop_preprocess_workshop_region_placeholder(&$variables)
{
    $regionClass = str_replace('_', '-', $variables['region']);

    $attr = new Attribute($variables['attributes']);
    $attr->addClass("workshop-region-placeholder");
    $attr->addClass("workshop-region-placeholder--{$regionClass}");
    $variables['attributes'] = $attr;

    $attr = new Attribute($variables['content_attributes']);
    $attr->addClass("workshop-region-placeholder__name");
    $variables['content_attributes'] = $attr;
}
